/**
 * ============================================
 *  DATOS DEL INVENTARIO DE VEHÍCULOS - SEMINUEVO
 * ============================================
 */

// ============================================
//  SEMINUEVOS - ENTREGA INMEDIATA (en Porlamar)
// ============================================
const vehiclesSeminuevos = [
    {
        id: 1,
        title: "Honda HR-V Sport 2025 4x4 AWD",
        price: "$36,000",
        year: 2025,
        km: "15,000 KM",
        engine: "2.0L",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "nacional",
        condition: "seminuevo",
        availability: "entrega_inmediata",
        badge: "ENTREGA INMEDIATA",
        images: [
            "images/gallery/honda-hrv-sport-2025-4x4-awd/1.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/2.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/3.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/4.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/5.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/6.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/7.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/8.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/9.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/10.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/11.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/12.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/13.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/14.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/15.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/16.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/17.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/18.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/19.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/20.jpg",
            "images/gallery/honda-hrv-sport-2025-4x4-awd/21.jpg"
        ],
        description: "Honda HR-V Sport 2025 con tracción 4x4 AWD. Motor 2.0L, transmisión automática. Ubicación Porlamar. Nivel de daño leve: golpe en puerta trasera piloto. 15,000 km recorridos. Entrega inmediata."
    },
    {
        id: 2,
        title: "Honda HR-V 2024 Sport",
        price: "$33,000",
        year: 2024,
        km: "25,000 KM",
        engine: "2.0L",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "nacional",
        condition: "seminuevo",
        availability: "entrega_inmediata",
        badge: "PUERTO LIBRE",
        images: [
            "images/gallery/honda-hrv-2024-sport/1.jpg",
            "images/gallery/honda-hrv-2024-sport/2.jpg",
            "images/gallery/honda-hrv-2024-sport/3.jpg",
            "images/gallery/honda-hrv-2024-sport/4.jpg",
            "images/gallery/honda-hrv-2024-sport/5.jpg",
            "images/gallery/honda-hrv-2024-sport/6.jpg",
            "images/gallery/honda-hrv-2024-sport/7.jpg",
            "images/gallery/honda-hrv-2024-sport/8.jpg",
            "images/gallery/honda-hrv-2024-sport/9.jpg",
            "images/gallery/honda-hrv-2024-sport/10.jpg",
            "images/gallery/honda-hrv-2024-sport/11.jpg",
            "images/gallery/honda-hrv-2024-sport/12.jpg",
            "images/gallery/honda-hrv-2024-sport/13.jpg",
            "images/gallery/honda-hrv-2024-sport/14.jpg",
            "images/gallery/honda-hrv-2024-sport/15.jpg",
            "images/gallery/honda-hrv-2024-sport/16.jpg",
            "images/gallery/honda-hrv-2024-sport/17.jpg",
            "images/gallery/honda-hrv-2024-sport/18.jpg",
            "images/gallery/honda-hrv-2024-sport/19.jpg",
            "images/gallery/honda-hrv-2024-sport/20.jpg",
            "images/gallery/honda-hrv-2024-sport/21.jpg",
            "images/gallery/honda-hrv-2024-sport/22.jpg",
            "images/gallery/honda-hrv-2024-sport/23.jpg",
            "images/gallery/honda-hrv-2024-sport/24.jpg"
        ],
        description: "Honda HR-V 2024 Sport. Motor 2.0L, automática. Ubicación Porlamar, Puerto Libre. Vehículo tuvo daño leve en esquina trasera izquierda. Entrega inmediata llave en mano. 25,000 km."
    },
    {
        id: 3,
        title: "Nissan Sentra SV 2025",
        price: "$26,000",
        year: 2025,
        km: "12,000 KM",
        engine: "2.0L",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "sedan",
        origin: "nacional",
        condition: "seminuevo",
        availability: "entrega_inmediata",
        badge: "PUERTO LIBRE",
        images: [
            "images/gallery/nissan-sentra-sv-2025/1.jpg",
            "images/gallery/nissan-sentra-sv-2025/2.jpg",
            "images/gallery/nissan-sentra-sv-2025/3.jpg",
            "images/gallery/nissan-sentra-sv-2025/4.jpg",
            "images/gallery/nissan-sentra-sv-2025/5.jpg",
            "images/gallery/nissan-sentra-sv-2025/6.jpg",
            "images/gallery/nissan-sentra-sv-2025/7.jpg",
            "images/gallery/nissan-sentra-sv-2025/8.jpg",
            "images/gallery/nissan-sentra-sv-2025/9.jpg",
            "images/gallery/nissan-sentra-sv-2025/10.jpg",
            "images/gallery/nissan-sentra-sv-2025/11.jpg",
            "images/gallery/nissan-sentra-sv-2025/12.jpg",
            "images/gallery/nissan-sentra-sv-2025/13.jpg",
            "images/gallery/nissan-sentra-sv-2025/14.jpg",
            "images/gallery/nissan-sentra-sv-2025/15.jpg",
            "images/gallery/nissan-sentra-sv-2025/16.jpg",
            "images/gallery/nissan-sentra-sv-2025/17.jpg"
        ],
        description: "Nissan Sentra SV 2025. Motor 2.0L, automático. Ubicación Porlamar, Puerto Libre. 12,000 km. Nivel de daño leve por granizo. Entrega inmediata."
    },
    {
        id: 4,
        title: "Nissan Rogue Sport 2019",
        price: "$22,000",
        year: 2019,
        km: "50,000 KM",
        engine: "2.0L",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "nacional",
        condition: "seminuevo",
        availability: "entrega_inmediata",
        badge: "SIN GOLPES",
        images: [
            "images/gallery/rogue-sport-2019/1.jpg",
            "images/gallery/rogue-sport-2019/2.jpg",
            "images/gallery/rogue-sport-2019/3.jpg",
            "images/gallery/rogue-sport-2019/4.jpg"
        ],
        description: "Nissan Rogue Sport 2019. Motor 2.0L, automática. 50,000 km. Ubicación Porlamar, Puerto Libre (lista para nacionalizar). Mantenimiento al día. Único dueño de concesionario, sin golpes."
    },
    {
        id: 5,
        title: "Toyota 4Runner 2021 SR5",
        price: "$39,990",
        year: 2021,
        km: "81,000 KM",
        engine: "4.0L V6",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "nacional",
        condition: "seminuevo",
        availability: "entrega_inmediata",
        badge: "4x2",
        images: [
            "images/gallery/toyota-4runner-2021-sr5/1.jpg",
            "images/gallery/toyota-4runner-2021-sr5/2.jpg",
            "images/gallery/toyota-4runner-2021-sr5/3.jpg",
            "images/gallery/toyota-4runner-2021-sr5/4.jpg",
            "images/gallery/toyota-4runner-2021-sr5/5.jpg",
            "images/gallery/toyota-4runner-2021-sr5/6.jpg",
            "images/gallery/toyota-4runner-2021-sr5/7.jpg",
            "images/gallery/toyota-4runner-2021-sr5/8.jpg",
            "images/gallery/toyota-4runner-2021-sr5/9.jpg",
            "images/gallery/toyota-4runner-2021-sr5/10.jpg",
            "images/gallery/toyota-4runner-2021-sr5/11.jpg",
            "images/gallery/toyota-4runner-2021-sr5/12.jpg",
            "images/gallery/toyota-4runner-2021-sr5/13.jpg",
            "images/gallery/toyota-4runner-2021-sr5/14.jpg",
            "images/gallery/toyota-4runner-2021-sr5/15.jpg",
            "images/gallery/toyota-4runner-2021-sr5/16.jpg",
            "images/gallery/toyota-4runner-2021-sr5/17.jpg",
            "images/gallery/toyota-4runner-2021-sr5/18.jpg"
        ],
        description: "Toyota 4Runner 2021 SR5. Motor 4.0L V6, automática, 4x2. 81,000 km. Ubicación Porlamar, Puerto Libre. Entrega inmediata. Nivel de daño medio: detalles estéticos, tuvo golpe en esquina trasera derecha."
    },
    {
        id: 6,
        title: "Toyota Corolla Cross LE 4x4 AWD 2022",
        price: "$31,990",
        year: 2022,
        km: "21,000 KM",
        engine: "2.0L",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "nacional",
        condition: "seminuevo",
        availability: "entrega_inmediata",
        badge: "PLACA NACIONAL",
        images: [
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/1.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/2.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/3.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/4.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/5.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/6.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/7.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/8.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/9.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/10.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/11.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/12.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/13.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/14.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/15.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/16.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/17.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/18.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/19.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/20.jpg",
            "images/gallery/toyota-corolla-cross-le-4x4-awd-2022/21.jpg"
        ],
        description: "Toyota Corolla Cross LE 4x4 AWD 2022. Motor 2.0L, automático. Placa nacional. 21,000 km. Ubicación Porlamar. Nivel de daño medio frontal derecho. Válvula EGR ya eliminada. Entrega inmediata."
    }
];

// ============================================
//  IMPORTADOS - POR PEDIDO (0KM y Bajo KM desde USA)
// ============================================
const vehicles0km = [
    {
        id: 101,
        title: "GMC Sierra 1500 AT4 4WD",
        price: "Consultar",
        year: 2026,
        km: "0 KM",
        engine: "Motor V8",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "pickup",
        origin: "importado",
        condition: "0km",
        availability: "por_pedido",
        badge: "🔥 POR PEDIDO",
        images: [
            "images/gallery/026-gmc-sierra-1500-short-bed-at4-4wd/1.jpeg",
            "images/gallery/026-gmc-sierra-1500-short-bed-at4-4wd/2.jpeg",
            "images/gallery/026-gmc-sierra-1500-short-bed-at4-4wd/3.jpeg",
            "images/gallery/026-gmc-sierra-1500-short-bed-at4-4wd/4.jpeg",
            "images/gallery/026-gmc-sierra-1500-short-bed-at4-4wd/5.jpeg",
            "images/gallery/026-gmc-sierra-1500-short-bed-at4-4wd/6.jpeg",
            "images/gallery/026-gmc-sierra-1500-short-bed-at4-4wd/7.jpeg",
            "images/gallery/026-gmc-sierra-1500-short-bed-at4-4wd/8.jpeg",
            "images/gallery/026-gmc-sierra-1500-short-bed-at4-4wd/9.jpeg",
            "images/gallery/026-gmc-sierra-1500-short-bed-at4-4wd/10.jpeg"
        ],
        description: "GMC Sierra 1500 AT4 4WD, Short Bed. Pickup premium con tracción 4x4. Importación directa desde USA. Precio + movilización, gastos de envío, aduana, impuestos y documentación."
    },
    {
        id: 102,
        title: "Jeep Wrangler Unlimited Sport S 4x4 2022",
        price: "Consultar",
        year: 2022,
        km: "Bajo KM",
        engine: "3.6L V6",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "POR PEDIDO",
        images: [
            "images/gallery/2022-jeep-wrangler-unlimited-sport-s-4x4/1.jpeg",
            "images/gallery/2022-jeep-wrangler-unlimited-sport-s-4x4/2.jpeg",
            "images/gallery/2022-jeep-wrangler-unlimited-sport-s-4x4/3.jpeg",
            "images/gallery/2022-jeep-wrangler-unlimited-sport-s-4x4/4.jpeg",
            "images/gallery/2022-jeep-wrangler-unlimited-sport-s-4x4/5.jpeg",
            "images/gallery/2022-jeep-wrangler-unlimited-sport-s-4x4/6.jpeg",
            "images/gallery/2022-jeep-wrangler-unlimited-sport-s-4x4/7.jpeg",
            "images/gallery/2022-jeep-wrangler-unlimited-sport-s-4x4/8.jpeg",
            "images/gallery/2022-jeep-wrangler-unlimited-sport-s-4x4/9.jpeg",
            "images/gallery/2022-jeep-wrangler-unlimited-sport-s-4x4/10.jpeg",
            "images/gallery/2022-jeep-wrangler-unlimited-sport-s-4x4/11.jpeg",
            "images/gallery/2022-jeep-wrangler-unlimited-sport-s-4x4/12.jpeg",
            "images/gallery/2022-jeep-wrangler-unlimited-sport-s-4x4/13.jpeg",
            "images/gallery/2022-jeep-wrangler-unlimited-sport-s-4x4/14.jpeg"
        ],
        description: "Jeep Wrangler Unlimited Sport S 2022, 4 puertas, 4x4. Motor 3.6L V6, automático. Importación desde USA. Precio + movilización, gastos de envío, aduana, impuestos y documentación."
    },
    {
        id: 103,
        title: "Lexus UX 200 2022",
        price: "Consultar",
        year: 2022,
        km: "Bajo KM",
        engine: "2.0L",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "PREMIUM",
        images: [
            "images/gallery/2022-lexus-ux-200/1.jpeg",
            "images/gallery/2022-lexus-ux-200/2.jpeg",
            "images/gallery/2022-lexus-ux-200/3.jpeg",
            "images/gallery/2022-lexus-ux-200/4.jpeg",
            "images/gallery/2022-lexus-ux-200/5.jpeg",
            "images/gallery/2022-lexus-ux-200/6.jpeg",
            "images/gallery/2022-lexus-ux-200/7.jpeg",
            "images/gallery/2022-lexus-ux-200/8.jpeg",
            "images/gallery/2022-lexus-ux-200/9.jpeg",
            "images/gallery/2022-lexus-ux-200/10.jpeg",
            "images/gallery/2022-lexus-ux-200/11.jpeg",
            "images/gallery/2022-lexus-ux-200/12.jpeg",
            "images/gallery/2022-lexus-ux-200/13.jpeg",
            "images/gallery/2022-lexus-ux-200/14.jpeg",
            "images/gallery/2022-lexus-ux-200/15.jpeg",
            "images/gallery/2022-lexus-ux-200/16.jpeg"
        ],
        description: "Lexus UX 200 2022. SUV premium compacto con motor 2.0L, transmisión automática. Importación directa desde USA. Precio + movilización, gastos de envío, aduana, impuestos y documentación."
    },
    {
        id: 104,
        title: "Hyundai Sonata SE 2023",
        price: "Consultar",
        year: 2023,
        km: "Bajo KM",
        engine: "2.5L",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "sedan",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "POR PEDIDO",
        images: [
            "images/gallery/2023-hyundai-sonata-se/1.jpeg",
            "images/gallery/2023-hyundai-sonata-se/2.jpeg",
            "images/gallery/2023-hyundai-sonata-se/3.jpeg",
            "images/gallery/2023-hyundai-sonata-se/4.jpeg",
            "images/gallery/2023-hyundai-sonata-se/5.jpeg",
            "images/gallery/2023-hyundai-sonata-se/6.jpeg",
            "images/gallery/2023-hyundai-sonata-se/7.jpeg",
            "images/gallery/2023-hyundai-sonata-se/8.jpeg",
            "images/gallery/2023-hyundai-sonata-se/9.jpeg",
            "images/gallery/2023-hyundai-sonata-se/10.jpeg",
            "images/gallery/2023-hyundai-sonata-se/11.jpeg",
            "images/gallery/2023-hyundai-sonata-se/12.jpeg",
            "images/gallery/2023-hyundai-sonata-se/13.jpeg",
            "images/gallery/2023-hyundai-sonata-se/14.jpeg",
            "images/gallery/2023-hyundai-sonata-se/15.jpeg",
            "images/gallery/2023-hyundai-sonata-se/16.jpeg",
            "images/gallery/2023-hyundai-sonata-se/17.jpeg"
        ],
        description: "Hyundai Sonata SE 2023. Sedán elegante con motor 2.5L, automático. Importación desde USA. Precio + movilización, gastos de envío, aduana, impuestos y documentación."
    },
    {
        id: 105,
        title: "Hyundai Tucson SEL 2023",
        price: "Consultar",
        year: 2023,
        km: "Bajo KM",
        engine: "2.5L I-4 187HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "POR PEDIDO",
        images: [
            "images/gallery/2023-hyundai-tucson-sel/1.jpeg",
            "images/gallery/2023-hyundai-tucson-sel/2.jpeg",
            "images/gallery/2023-hyundai-tucson-sel/3.jpeg",
            "images/gallery/2023-hyundai-tucson-sel/4.jpeg",
            "images/gallery/2023-hyundai-tucson-sel/5.jpeg",
            "images/gallery/2023-hyundai-tucson-sel/6.jpeg",
            "images/gallery/2023-hyundai-tucson-sel/7.jpeg",
            "images/gallery/2023-hyundai-tucson-sel/8.jpeg",
            "images/gallery/2023-hyundai-tucson-sel/9.jpeg",
            "images/gallery/2023-hyundai-tucson-sel/10.jpeg",
            "images/gallery/2023-hyundai-tucson-sel/11.jpeg",
            "images/gallery/2023-hyundai-tucson-sel/12.jpeg",
            "images/gallery/2023-hyundai-tucson-sel/13.jpeg",
            "images/gallery/2023-hyundai-tucson-sel/14.jpeg",
            "images/gallery/2023-hyundai-tucson-sel/15.jpeg"
        ],
        description: "Hyundai Tucson SEL 2023. SUV con motor 2.5L de 187HP, automática. Importación desde USA. Precio + movilización, gastos de envío, aduana, impuestos y documentación."
    },
    {
        id: 106,
        title: "Isuzu NPR HD 2023",
        price: "Consultar",
        year: 2023,
        km: "Bajo KM",
        engine: "Diésel",
        transmission: "Automático",
        fuel: "Diésel",
        bodyType: "pickup",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "COMERCIAL",
        images: [
            "images/gallery/2023-isuzu-npr-hd/1.jpeg",
            "images/gallery/2023-isuzu-npr-hd/2.jpeg",
            "images/gallery/2023-isuzu-npr-hd/3.jpeg",
            "images/gallery/2023-isuzu-npr-hd/4.jpeg",
            "images/gallery/2023-isuzu-npr-hd/5.jpeg",
            "images/gallery/2023-isuzu-npr-hd/6.jpeg",
            "images/gallery/2023-isuzu-npr-hd/7.jpeg",
            "images/gallery/2023-isuzu-npr-hd/8.jpeg",
            "images/gallery/2023-isuzu-npr-hd/9.jpeg",
            "images/gallery/2023-isuzu-npr-hd/10.jpeg",
            "images/gallery/2023-isuzu-npr-hd/11.jpeg",
            "images/gallery/2023-isuzu-npr-hd/12.jpeg",
            "images/gallery/2023-isuzu-npr-hd/13.jpeg"
        ],
        description: "Isuzu NPR HD 2023. Camión comercial diésel, ideal para trabajo pesado. Importación directa desde USA. Precio + movilización, gastos de envío, aduana, impuestos y documentación."
    },
    {
        id: 107,
        title: "Jeep Wrangler Willys Sport 4x4 2023",
        price: "Consultar",
        year: 2023,
        km: "Bajo KM",
        engine: "3.6L V6",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "2 PUERTAS",
        images: [
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/1.jpeg",
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/2.jpeg",
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/3.jpeg",
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/4.jpeg",
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/5.jpeg",
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/6.jpeg",
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/7.jpeg",
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/8.jpeg",
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/9.jpeg",
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/10.jpeg",
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/11.jpeg",
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/12.jpeg",
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/13.jpeg",
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/14.jpeg",
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/15.jpeg",
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/16.jpeg",
            "images/gallery/2023-jeep-wrangler-2-door-willys-sport-4x4/17.jpeg"
        ],
        description: "Jeep Wrangler Willys Sport 2023, 2 puertas, 4x4. Motor 3.6L V6. El clásico todoterreno. Importación desde USA. Precio + movilización, gastos de envío, aduana, impuestos y documentación."
    },
    {
        id: 108,
        title: "Range Rover Evoque R-Dynamic S 2023",
        price: "Consultar",
        year: 2023,
        km: "Bajo KM",
        engine: "2.0L Turbo",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "🔥 PREMIUM",
        images: [
            "images/gallery/2023-land-rover-range-rover-evoque-r-dynamic-s/1.jpeg",
            "images/gallery/2023-land-rover-range-rover-evoque-r-dynamic-s/2.jpeg",
            "images/gallery/2023-land-rover-range-rover-evoque-r-dynamic-s/3.jpeg",
            "images/gallery/2023-land-rover-range-rover-evoque-r-dynamic-s/4.jpeg",
            "images/gallery/2023-land-rover-range-rover-evoque-r-dynamic-s/5.jpeg",
            "images/gallery/2023-land-rover-range-rover-evoque-r-dynamic-s/6.jpeg",
            "images/gallery/2023-land-rover-range-rover-evoque-r-dynamic-s/7.jpeg",
            "images/gallery/2023-land-rover-range-rover-evoque-r-dynamic-s/8.jpeg",
            "images/gallery/2023-land-rover-range-rover-evoque-r-dynamic-s/9.jpeg",
            "images/gallery/2023-land-rover-range-rover-evoque-r-dynamic-s/10.jpeg",
            "images/gallery/2023-land-rover-range-rover-evoque-r-dynamic-s/11.jpeg",
            "images/gallery/2023-land-rover-range-rover-evoque-r-dynamic-s/12.jpeg",
            "images/gallery/2023-land-rover-range-rover-evoque-r-dynamic-s/13.jpeg",
            "images/gallery/2023-land-rover-range-rover-evoque-r-dynamic-s/14.jpeg",
            "images/gallery/2023-land-rover-range-rover-evoque-r-dynamic-s/15.jpeg"
        ],
        description: "Land Rover Range Rover Evoque R-Dynamic S 2023. SUV de lujo con motor 2.0L Turbo, automático. Importación directa desde USA. Precio + movilización, gastos de envío, aduana, impuestos y documentación."
    },
    {
        id: 109,
        title: "Chevrolet Silverado 1500 LT 2024",
        price: "Consultar",
        year: 2024,
        km: "Bajo KM",
        engine: "V8",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "pickup",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "POR PEDIDO",
        images: [
            "images/gallery/2024-chevrolet-silverado-1500-2wd-standard-bed-lt/1.jpeg",
            "images/gallery/2024-chevrolet-silverado-1500-2wd-standard-bed-lt/2.jpeg",
            "images/gallery/2024-chevrolet-silverado-1500-2wd-standard-bed-lt/3.jpeg",
            "images/gallery/2024-chevrolet-silverado-1500-2wd-standard-bed-lt/4.jpeg",
            "images/gallery/2024-chevrolet-silverado-1500-2wd-standard-bed-lt/5.jpeg",
            "images/gallery/2024-chevrolet-silverado-1500-2wd-standard-bed-lt/6.jpeg",
            "images/gallery/2024-chevrolet-silverado-1500-2wd-standard-bed-lt/7.jpeg",
            "images/gallery/2024-chevrolet-silverado-1500-2wd-standard-bed-lt/8.jpeg",
            "images/gallery/2024-chevrolet-silverado-1500-2wd-standard-bed-lt/9.jpeg",
            "images/gallery/2024-chevrolet-silverado-1500-2wd-standard-bed-lt/10.jpeg",
            "images/gallery/2024-chevrolet-silverado-1500-2wd-standard-bed-lt/11.jpeg",
            "images/gallery/2024-chevrolet-silverado-1500-2wd-standard-bed-lt/12.jpeg",
            "images/gallery/2024-chevrolet-silverado-1500-2wd-standard-bed-lt/13.jpeg",
            "images/gallery/2024-chevrolet-silverado-1500-2wd-standard-bed-lt/14.jpeg",
            "images/gallery/2024-chevrolet-silverado-1500-2wd-standard-bed-lt/15.jpeg",
            "images/gallery/2024-chevrolet-silverado-1500-2wd-standard-bed-lt/16.jpeg"
        ],
        description: "Chevrolet Silverado 1500 LT 2024, 2WD, Standard Bed. Pickup full size, automática. Importación desde USA. Precio + movilización, gastos de envío, aduana, impuestos y documentación."
    },
    {
        id: 110,
        title: "Ford F-150 XL 2024",
        price: "Consultar",
        year: 2024,
        km: "Bajo KM",
        engine: "V6/V8",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "pickup",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "POR PEDIDO",
        images: [
            "images/gallery/2024-ford-f-150-xl/1.jpeg",
            "images/gallery/2024-ford-f-150-xl/2.jpeg",
            "images/gallery/2024-ford-f-150-xl/3.jpeg",
            "images/gallery/2024-ford-f-150-xl/4.jpeg",
            "images/gallery/2024-ford-f-150-xl/5.jpeg",
            "images/gallery/2024-ford-f-150-xl/6.jpeg",
            "images/gallery/2024-ford-f-150-xl/7.jpeg",
            "images/gallery/2024-ford-f-150-xl/8.jpeg",
            "images/gallery/2024-ford-f-150-xl/9.jpeg"
        ],
        description: "Ford F-150 XL 2024. La pickup más vendida de América. Automática. Importación directa desde USA. Precio + movilización, gastos de envío, aduana, impuestos y documentación."
    },
    {
        id: 111,
        title: "Hyundai Santa Cruz SEL 2024",
        price: "Consultar",
        year: 2024,
        km: "Bajo KM",
        engine: "2.5L",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "pickup",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "POR PEDIDO",
        images: [
            "images/gallery/2024-hyundai-santa-cruz-sel/1.jpeg",
            "images/gallery/2024-hyundai-santa-cruz-sel/2.jpeg",
            "images/gallery/2024-hyundai-santa-cruz-sel/3.jpeg",
            "images/gallery/2024-hyundai-santa-cruz-sel/4.jpeg",
            "images/gallery/2024-hyundai-santa-cruz-sel/5.jpeg",
            "images/gallery/2024-hyundai-santa-cruz-sel/6.jpeg",
            "images/gallery/2024-hyundai-santa-cruz-sel/7.jpeg",
            "images/gallery/2024-hyundai-santa-cruz-sel/8.jpeg",
            "images/gallery/2024-hyundai-santa-cruz-sel/9.jpeg",
            "images/gallery/2024-hyundai-santa-cruz-sel/10.jpeg",
            "images/gallery/2024-hyundai-santa-cruz-sel/11.jpeg",
            "images/gallery/2024-hyundai-santa-cruz-sel/12.jpeg",
            "images/gallery/2024-hyundai-santa-cruz-sel/13.jpeg",
            "images/gallery/2024-hyundai-santa-cruz-sel/14.jpeg",
            "images/gallery/2024-hyundai-santa-cruz-sel/15.jpeg"
        ],
        description: "Hyundai Santa Cruz SEL 2024. Pickup-SUV moderna con motor 2.5L, automática. Importación desde USA. Precio + movilización, gastos de envío, aduana, impuestos y documentación."
    },
    {
        id: 112,
        title: "Hyundai Sonata SEL 2024",
        price: "Consultar",
        year: 2024,
        km: "Bajo KM",
        engine: "2.5L",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "sedan",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "POR PEDIDO",
        images: [
            "images/gallery/2024-hyundai-sonata-sel/1.jpeg",
            "images/gallery/2024-hyundai-sonata-sel/2.jpeg",
            "images/gallery/2024-hyundai-sonata-sel/3.jpeg",
            "images/gallery/2024-hyundai-sonata-sel/4.jpeg",
            "images/gallery/2024-hyundai-sonata-sel/5.jpeg",
            "images/gallery/2024-hyundai-sonata-sel/6.jpeg",
            "images/gallery/2024-hyundai-sonata-sel/7.jpeg",
            "images/gallery/2024-hyundai-sonata-sel/8.jpeg",
            "images/gallery/2024-hyundai-sonata-sel/9.jpeg",
            "images/gallery/2024-hyundai-sonata-sel/10.jpeg",
            "images/gallery/2024-hyundai-sonata-sel/11.jpeg",
            "images/gallery/2024-hyundai-sonata-sel/12.jpeg",
            "images/gallery/2024-hyundai-sonata-sel/13.jpeg",
            "images/gallery/2024-hyundai-sonata-sel/14.jpeg",
            "images/gallery/2024-hyundai-sonata-sel/15.jpeg"
        ],
        description: "Hyundai Sonata SEL 2024. Sedán premium con motor 2.5L, automático. Importación desde USA. Precio + movilización, gastos de envío, aduana, impuestos y documentación."
    },
    {
        id: 113,
        title: "Chevrolet Silverado 1500 Trail Boss 4WD 2025",
        price: "Consultar",
        year: 2025,
        km: "Bajo KM",
        engine: "V8",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "pickup",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "🔥 TRAIL BOSS",
        images: [
            "images/gallery/2025-chevrolet-silverado-1500-4wd-short-bed-custom-trail-boss/1.jpeg",
            "images/gallery/2025-chevrolet-silverado-1500-4wd-short-bed-custom-trail-boss/2.jpeg",
            "images/gallery/2025-chevrolet-silverado-1500-4wd-short-bed-custom-trail-boss/3.jpeg",
            "images/gallery/2025-chevrolet-silverado-1500-4wd-short-bed-custom-trail-boss/4.jpeg",
            "images/gallery/2025-chevrolet-silverado-1500-4wd-short-bed-custom-trail-boss/5.jpeg",
            "images/gallery/2025-chevrolet-silverado-1500-4wd-short-bed-custom-trail-boss/6.jpeg",
            "images/gallery/2025-chevrolet-silverado-1500-4wd-short-bed-custom-trail-boss/7.jpeg",
            "images/gallery/2025-chevrolet-silverado-1500-4wd-short-bed-custom-trail-boss/8.jpeg",
            "images/gallery/2025-chevrolet-silverado-1500-4wd-short-bed-custom-trail-boss/9.jpeg",
            "images/gallery/2025-chevrolet-silverado-1500-4wd-short-bed-custom-trail-boss/10.jpeg",
            "images/gallery/2025-chevrolet-silverado-1500-4wd-short-bed-custom-trail-boss/11.jpeg",
            "images/gallery/2025-chevrolet-silverado-1500-4wd-short-bed-custom-trail-boss/12.jpeg",
            "images/gallery/2025-chevrolet-silverado-1500-4wd-short-bed-custom-trail-boss/13.jpeg",
            "images/gallery/2025-chevrolet-silverado-1500-4wd-short-bed-custom-trail-boss/14.jpeg",
            "images/gallery/2025-chevrolet-silverado-1500-4wd-short-bed-custom-trail-boss/15.jpeg",
            "images/gallery/2025-chevrolet-silverado-1500-4wd-short-bed-custom-trail-boss/16.jpeg"
        ],
        description: "Chevrolet Silverado 1500 Custom Trail Boss 2025, 4WD, Short Bed. Pickup todoterreno V8, automática. Importación desde USA. Precio + movilización, gastos de envío, aduana e impuestos."
    },
    {
        id: 114,
        title: "Chevrolet Trax FWD 1RS 2025",
        price: "Consultar",
        year: 2025,
        km: "Bajo KM",
        engine: "1.2L Turbo",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "POR PEDIDO",
        images: [
            "images/gallery/2025-chevrolet-trax-fwd-1rs/1.jpeg",
            "images/gallery/2025-chevrolet-trax-fwd-1rs/2.jpeg",
            "images/gallery/2025-chevrolet-trax-fwd-1rs/3.jpeg",
            "images/gallery/2025-chevrolet-trax-fwd-1rs/4.jpeg",
            "images/gallery/2025-chevrolet-trax-fwd-1rs/5.jpeg",
            "images/gallery/2025-chevrolet-trax-fwd-1rs/6.jpeg",
            "images/gallery/2025-chevrolet-trax-fwd-1rs/7.jpeg",
            "images/gallery/2025-chevrolet-trax-fwd-1rs/8.jpeg",
            "images/gallery/2025-chevrolet-trax-fwd-1rs/9.jpeg",
            "images/gallery/2025-chevrolet-trax-fwd-1rs/10.jpeg",
            "images/gallery/2025-chevrolet-trax-fwd-1rs/11.jpeg",
            "images/gallery/2025-chevrolet-trax-fwd-1rs/12.jpeg",
            "images/gallery/2025-chevrolet-trax-fwd-1rs/13.jpeg",
            "images/gallery/2025-chevrolet-trax-fwd-1rs/14.jpeg",
            "images/gallery/2025-chevrolet-trax-fwd-1rs/15.jpeg"
        ],
        description: "Chevrolet Trax 1RS 2025. SUV compacto con motor 1.2L Turbo, automático. Importación desde USA. Precio + movilización, gastos de envío, aduana, impuestos y documentación."
    },
    {
        id: 115,
        title: "Ford Maverick Tremor 2025",
        price: "Consultar",
        year: 2025,
        km: "Bajo KM",
        engine: "2.0L Turbo",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "pickup",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "🔥 TREMOR",
        images: [
            "images/gallery/2025-ford-maverick-tremor/1.jpeg",
            "images/gallery/2025-ford-maverick-tremor/2.jpeg",
            "images/gallery/2025-ford-maverick-tremor/3.jpeg",
            "images/gallery/2025-ford-maverick-tremor/4.jpeg",
            "images/gallery/2025-ford-maverick-tremor/5.jpeg",
            "images/gallery/2025-ford-maverick-tremor/6.jpeg",
            "images/gallery/2025-ford-maverick-tremor/7.jpeg",
            "images/gallery/2025-ford-maverick-tremor/8.jpeg",
            "images/gallery/2025-ford-maverick-tremor/9.jpeg",
            "images/gallery/2025-ford-maverick-tremor/10.jpeg",
            "images/gallery/2025-ford-maverick-tremor/11.jpeg",
            "images/gallery/2025-ford-maverick-tremor/12.jpeg",
            "images/gallery/2025-ford-maverick-tremor/13.jpeg",
            "images/gallery/2025-ford-maverick-tremor/14.jpeg",
            "images/gallery/2025-ford-maverick-tremor/15.jpeg",
            "images/gallery/2025-ford-maverick-tremor/16.jpeg",
            "images/gallery/2025-ford-maverick-tremor/17.jpeg"
        ],
        description: "Ford Maverick Tremor 2025. Pickup compacta con paquete off-road Tremor, motor 2.0L Turbo, automática. Importación desde USA. Precio + movilización, gastos de envío, aduana e impuestos."
    },
    {
        id: 116,
        title: "Ford Transit-150 2025",
        price: "Consultar",
        year: 2025,
        km: "Bajo KM",
        engine: "3.5L V6",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "pickup",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "COMERCIAL",
        images: [
            "images/gallery/2025-ford-transit-150/1.jpeg",
            "images/gallery/2025-ford-transit-150/2.jpeg",
            "images/gallery/2025-ford-transit-150/3.jpeg",
            "images/gallery/2025-ford-transit-150/4.jpeg",
            "images/gallery/2025-ford-transit-150/5.jpeg",
            "images/gallery/2025-ford-transit-150/6.jpeg",
            "images/gallery/2025-ford-transit-150/7.jpeg",
            "images/gallery/2025-ford-transit-150/8.jpeg",
            "images/gallery/2025-ford-transit-150/9.jpeg",
            "images/gallery/2025-ford-transit-150/10.jpeg",
            "images/gallery/2025-ford-transit-150/11.jpeg",
            "images/gallery/2025-ford-transit-150/12.jpeg",
            "images/gallery/2025-ford-transit-150/13.jpeg",
            "images/gallery/2025-ford-transit-150/14.jpeg",
            "images/gallery/2025-ford-transit-150/15.jpeg"
        ],
        description: "Ford Transit-150 2025. Van comercial ideal para carga o pasajeros. Motor 3.5L V6, automática. Importación desde USA. Precio + movilización, gastos de envío, aduana e impuestos."
    },
    {
        id: 117,
        title: "Honda Odyssey EX-L 2025",
        price: "Consultar",
        year: 2025,
        km: "Bajo KM",
        engine: "3.5L V6",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "FAMILIAR",
        images: [
            "images/gallery/2025-honda-odyssey-ex-l/1.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l/2.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l/3.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l/4.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l/5.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l/6.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l/7.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l/8.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l/9.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l/10.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l/11.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l/12.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l/13.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l/14.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l/15.jpeg"
        ],
        description: "Honda Odyssey EX-L 2025. Minivan premium con motor 3.5L V6, automática. Interior en cuero. Importación desde USA. Precio + movilización, gastos de envío, aduana e impuestos."
    },
    {
        id: 118,
        title: "Honda Odyssey EX-L 2025 (Negra)",
        price: "Consultar",
        year: 2025,
        km: "Bajo KM",
        engine: "3.5L V6",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "FAMILIAR",
        images: [
            "images/gallery/2025-honda-odyssey-ex-l-negr/1.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l-negr/2.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l-negr/3.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l-negr/4.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l-negr/5.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l-negr/6.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l-negr/7.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l-negr/8.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l-negr/9.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l-negr/10.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l-negr/11.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l-negr/12.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l-negr/13.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l-negr/14.jpeg",
            "images/gallery/2025-honda-odyssey-ex-l-negr/15.jpeg"
        ],
        description: "Honda Odyssey EX-L 2025 color negro. Minivan premium con motor 3.5L V6, automática. Interior en cuero. Importación desde USA. Precio + movilización, gastos de envío, aduana e impuestos."
    },
    {
        id: 119,
        title: "Hyundai Elantra Hybrid Blue 2025",
        price: "$15,280+",
        year: 2025,
        km: "29,400 KM",
        engine: "1.6L I-4 104HP",
        transmission: "Automático",
        fuel: "Híbrido",
        bodyType: "sedan",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "⚡ HÍBRIDO",
        images: [
            "images/gallery/2025-hyundai-elantra-hybrid-blue/1.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/2.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/3.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/4.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/5.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/6.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/7.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/8.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/9.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/10.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/11.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/12.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/13.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/14.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/15.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/16.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/17.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/18.jpeg",
            "images/gallery/2025-hyundai-elantra-hybrid-blue/19.jpeg"
        ],
        description: "Hyundai Elantra Hybrid Blue 2025. Motor 1.6L I-4 de 104HP, automático. Daño izquierdo frontal. Airbags intactos. 29,400 km. Precio $15,280 + movilización, envío, aduana e impuestos."
    },
    {
        id: 120,
        title: "Hyundai Elantra N 2025",
        price: "$15,400+",
        year: 2025,
        km: "49,400 KM",
        engine: "2.0L Turbo 276HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "sedan",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "🔥 276HP",
        images: [
            "images/gallery/2025-hyundai-elantra-n/1.jpeg",
            "images/gallery/2025-hyundai-elantra-n/2.jpeg",
            "images/gallery/2025-hyundai-elantra-n/3.jpeg",
            "images/gallery/2025-hyundai-elantra-n/4.jpeg",
            "images/gallery/2025-hyundai-elantra-n/5.jpeg",
            "images/gallery/2025-hyundai-elantra-n/6.jpeg",
            "images/gallery/2025-hyundai-elantra-n/7.jpeg",
            "images/gallery/2025-hyundai-elantra-n/8.jpeg",
            "images/gallery/2025-hyundai-elantra-n/9.jpeg",
            "images/gallery/2025-hyundai-elantra-n/10.jpeg",
            "images/gallery/2025-hyundai-elantra-n/11.jpeg",
            "images/gallery/2025-hyundai-elantra-n/12.jpeg",
            "images/gallery/2025-hyundai-elantra-n/13.jpeg",
            "images/gallery/2025-hyundai-elantra-n/14.jpeg",
            "images/gallery/2025-hyundai-elantra-n/15.jpeg",
            "images/gallery/2025-hyundai-elantra-n/16.jpeg",
            "images/gallery/2025-hyundai-elantra-n/17.jpeg"
        ],
        description: "Hyundai Elantra N 2025. Motor 2.0L Turbo de 276HP, automático. Daño frontal y trasero. Falta convertidor catalítico. Airbags intactos. 49,400 km. Precio $15,400 + movilización, envío, aduana e impuestos."
    },
    {
        id: 121,
        title: "Hyundai Kona SEL 2025",
        price: "$12,100+",
        year: 2025,
        km: "43,100 KM",
        engine: "2.0L I-4 147HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "POR PEDIDO",
        images: [
            "images/gallery/2025-hyundai-kona-sel/1.jpeg",
            "images/gallery/2025-hyundai-kona-sel/2.jpeg",
            "images/gallery/2025-hyundai-kona-sel/3.jpeg",
            "images/gallery/2025-hyundai-kona-sel/4.jpeg",
            "images/gallery/2025-hyundai-kona-sel/5.jpeg",
            "images/gallery/2025-hyundai-kona-sel/6.jpeg",
            "images/gallery/2025-hyundai-kona-sel/7.jpeg",
            "images/gallery/2025-hyundai-kona-sel/8.jpeg",
            "images/gallery/2025-hyundai-kona-sel/9.jpeg",
            "images/gallery/2025-hyundai-kona-sel/10.jpeg",
            "images/gallery/2025-hyundai-kona-sel/11.jpeg",
            "images/gallery/2025-hyundai-kona-sel/12.jpeg",
            "images/gallery/2025-hyundai-kona-sel/13.jpeg",
            "images/gallery/2025-hyundai-kona-sel/14.jpeg",
            "images/gallery/2025-hyundai-kona-sel/15.jpeg",
            "images/gallery/2025-hyundai-kona-sel/16.jpeg"
        ],
        description: "Hyundai Kona SEL 2025. Motor 2.0L I-4 de 147HP, automática. Daño leve lado derecho. Airbags explotados. 43,100 km. Precio $12,100 + movilización, envío, aduana e impuestos."
    },
    {
        id: 122,
        title: "Hyundai Tucson SEL 2025",
        price: "$14,860+",
        year: 2025,
        km: "52,200 KM",
        engine: "2.5L I-4 187HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "POR PEDIDO",
        images: [
            "images/gallery/2025-hyundai-tucson-sel/1.jpeg",
            "images/gallery/2025-hyundai-tucson-sel/2.jpeg",
            "images/gallery/2025-hyundai-tucson-sel/3.jpeg",
            "images/gallery/2025-hyundai-tucson-sel/4.jpeg",
            "images/gallery/2025-hyundai-tucson-sel/5.jpeg",
            "images/gallery/2025-hyundai-tucson-sel/6.jpeg",
            "images/gallery/2025-hyundai-tucson-sel/7.jpeg",
            "images/gallery/2025-hyundai-tucson-sel/8.jpeg",
            "images/gallery/2025-hyundai-tucson-sel/9.jpeg",
            "images/gallery/2025-hyundai-tucson-sel/10.jpeg",
            "images/gallery/2025-hyundai-tucson-sel/11.jpeg",
            "images/gallery/2025-hyundai-tucson-sel/12.jpeg",
            "images/gallery/2025-hyundai-tucson-sel/13.jpeg",
            "images/gallery/2025-hyundai-tucson-sel/14.jpeg",
            "images/gallery/2025-hyundai-tucson-sel/15.jpeg",
            "images/gallery/2025-hyundai-tucson-sel/16.jpeg"
        ],
        description: "Hyundai Tucson SEL 2025. Motor 2.5L I-4 de 187HP, automática. Daño trasero. Airbags intactos. 52,200 km. Precio $14,860 + movilización, envío, aduana e impuestos."
    },
    {
        id: 123,
        title: "Hyundai Tucson SEL Convenience 2025",
        price: "$11,950+",
        year: 2025,
        km: "68,500 KM",
        engine: "2.5L I-4 187HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "POR PEDIDO",
        images: [
            "images/gallery/2025-hyundai-tucson-sel-convenience/1.jpeg",
            "images/gallery/2025-hyundai-tucson-sel-convenience/2.jpeg",
            "images/gallery/2025-hyundai-tucson-sel-convenience/3.jpeg",
            "images/gallery/2025-hyundai-tucson-sel-convenience/4.jpeg",
            "images/gallery/2025-hyundai-tucson-sel-convenience/5.jpeg",
            "images/gallery/2025-hyundai-tucson-sel-convenience/6.jpeg",
            "images/gallery/2025-hyundai-tucson-sel-convenience/7.jpeg",
            "images/gallery/2025-hyundai-tucson-sel-convenience/8.jpeg",
            "images/gallery/2025-hyundai-tucson-sel-convenience/9.jpeg",
            "images/gallery/2025-hyundai-tucson-sel-convenience/10.jpeg",
            "images/gallery/2025-hyundai-tucson-sel-convenience/11.jpeg",
            "images/gallery/2025-hyundai-tucson-sel-convenience/12.jpeg",
            "images/gallery/2025-hyundai-tucson-sel-convenience/13.jpeg",
            "images/gallery/2025-hyundai-tucson-sel-convenience/14.jpeg",
            "images/gallery/2025-hyundai-tucson-sel-convenience/15.jpeg"
        ],
        description: "Hyundai Tucson SEL Convenience 2025. Motor 2.5L I-4 de 187HP, automático. Daño frontal. Airbags explotados. 68,500 km. Precio $11,950 + movilización, envío, aduana e impuestos."
    },
    {
        id: 124,
        title: "Kia K5 GT-Line 2025",
        price: "$16,360+",
        year: 2025,
        km: "32,200 KM",
        engine: "2.5L I-4 191HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "sedan",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "GT-LINE",
        images: [
            "images/gallery/2025-kia-k5-gt-line/1.jpeg",
            "images/gallery/2025-kia-k5-gt-line/2.jpeg",
            "images/gallery/2025-kia-k5-gt-line/3.jpeg",
            "images/gallery/2025-kia-k5-gt-line/4.jpeg",
            "images/gallery/2025-kia-k5-gt-line/5.jpeg",
            "images/gallery/2025-kia-k5-gt-line/6.jpeg",
            "images/gallery/2025-kia-k5-gt-line/7.jpeg",
            "images/gallery/2025-kia-k5-gt-line/8.jpeg",
            "images/gallery/2025-kia-k5-gt-line/9.jpeg",
            "images/gallery/2025-kia-k5-gt-line/10.jpeg",
            "images/gallery/2025-kia-k5-gt-line/11.jpeg",
            "images/gallery/2025-kia-k5-gt-line/12.jpeg",
            "images/gallery/2025-kia-k5-gt-line/13.jpeg",
            "images/gallery/2025-kia-k5-gt-line/14.jpeg",
            "images/gallery/2025-kia-k5-gt-line/15.jpeg",
            "images/gallery/2025-kia-k5-gt-line/16.jpeg",
            "images/gallery/2025-kia-k5-gt-line/17.jpeg"
        ],
        description: "Kia K5 GT-Line 2025. Motor 2.5L I-4 de 191HP, automático. Daño trasero. Airbags intactos. 32,200 km. Precio $16,360 + movilización, envío, aduana e impuestos."
    },
    {
        id: 125,
        title: "Lexus GX 550 Overtrail+ 2025",
        price: "$79,940+",
        year: 2025,
        km: "10,400 KM",
        engine: "3.4L V6 Turbo 349HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "🔥 EXCLUSIVO",
        images: [
            "images/gallery/2025-lexus-gx-550-overtrail/1.jpeg",
            "images/gallery/2025-lexus-gx-550-overtrail/2.jpeg",
            "images/gallery/2025-lexus-gx-550-overtrail/3.jpeg",
            "images/gallery/2025-lexus-gx-550-overtrail/4.jpeg",
            "images/gallery/2025-lexus-gx-550-overtrail/5.jpeg",
            "images/gallery/2025-lexus-gx-550-overtrail/6.jpeg",
            "images/gallery/2025-lexus-gx-550-overtrail/7.jpeg",
            "images/gallery/2025-lexus-gx-550-overtrail/8.jpeg",
            "images/gallery/2025-lexus-gx-550-overtrail/9.jpeg",
            "images/gallery/2025-lexus-gx-550-overtrail/10.jpeg",
            "images/gallery/2025-lexus-gx-550-overtrail/11.jpeg",
            "images/gallery/2025-lexus-gx-550-overtrail/12.jpeg",
            "images/gallery/2025-lexus-gx-550-overtrail/13.jpeg",
            "images/gallery/2025-lexus-gx-550-overtrail/14.jpeg",
            "images/gallery/2025-lexus-gx-550-overtrail/15.jpeg",
            "images/gallery/2025-lexus-gx-550-overtrail/16.jpeg"
        ],
        description: "Lexus GX 550 Overtrail+ 2025. Motor 3.4L V6 Turbo de 349HP, automática, 4x4. Daño lateral derecho. Airbags explotados. 10,400 km. Precio $79,940 + movilización, envío, aduana e impuestos."
    },
    {
        id: 126,
        title: "Lexus RC 350 F Sport 2025",
        price: "$23,800+",
        year: 2025,
        km: "4,300 KM",
        engine: "3.5L V6 311HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "coupe",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "🔥 JUGUETE",
        images: [
            "images/gallery/2025-lexus-rc-350-f-sport/1.jpeg",
            "images/gallery/2025-lexus-rc-350-f-sport/2.jpeg",
            "images/gallery/2025-lexus-rc-350-f-sport/3.jpeg",
            "images/gallery/2025-lexus-rc-350-f-sport/4.jpeg",
            "images/gallery/2025-lexus-rc-350-f-sport/5.jpeg",
            "images/gallery/2025-lexus-rc-350-f-sport/6.jpeg",
            "images/gallery/2025-lexus-rc-350-f-sport/7.jpeg",
            "images/gallery/2025-lexus-rc-350-f-sport/8.jpeg",
            "images/gallery/2025-lexus-rc-350-f-sport/9.jpeg",
            "images/gallery/2025-lexus-rc-350-f-sport/10.jpeg",
            "images/gallery/2025-lexus-rc-350-f-sport/11.jpeg",
            "images/gallery/2025-lexus-rc-350-f-sport/12.jpeg",
            "images/gallery/2025-lexus-rc-350-f-sport/13.jpeg",
            "images/gallery/2025-lexus-rc-350-f-sport/14.jpeg",
            "images/gallery/2025-lexus-rc-350-f-sport/15.jpeg",
            "images/gallery/2025-lexus-rc-350-f-sport/16.jpeg",
            "images/gallery/2025-lexus-rc-350-f-sport/17.jpeg"
        ],
        description: "Lexus RC 350 F Sport 2025. ¡JUGUETE! Motor 3.5L V6 de 311HP, automático, tracción trasera. Daño frontal. Airbags explotados. Solo 4,300 km. Precio $23,800 + movilización, envío, aduana e impuestos."
    },
    {
        id: 127,
        title: "Lexus TX 350 Premium 2025",
        price: "$40,440+",
        year: 2025,
        km: "18,100 KM",
        engine: "2.4L Turbo 275HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "PREMIUM",
        images: [
            "images/gallery/2025-lexus-tx-350-premium/1.jpeg",
            "images/gallery/2025-lexus-tx-350-premium/2.jpeg",
            "images/gallery/2025-lexus-tx-350-premium/3.jpeg",
            "images/gallery/2025-lexus-tx-350-premium/4.jpeg",
            "images/gallery/2025-lexus-tx-350-premium/5.jpeg",
            "images/gallery/2025-lexus-tx-350-premium/6.jpeg",
            "images/gallery/2025-lexus-tx-350-premium/7.jpeg",
            "images/gallery/2025-lexus-tx-350-premium/8.jpeg",
            "images/gallery/2025-lexus-tx-350-premium/9.jpeg",
            "images/gallery/2025-lexus-tx-350-premium/10.jpeg",
            "images/gallery/2025-lexus-tx-350-premium/11.jpeg",
            "images/gallery/2025-lexus-tx-350-premium/12.jpeg",
            "images/gallery/2025-lexus-tx-350-premium/13.jpeg",
            "images/gallery/2025-lexus-tx-350-premium/14.jpeg",
            "images/gallery/2025-lexus-tx-350-premium/15.jpeg",
            "images/gallery/2025-lexus-tx-350-premium/16.jpeg"
        ],
        description: "Lexus TX 350 Premium 2025. Motor 2.4L Turbo de 275HP, automática, 4x4. Daño lateral derecho. Airbags explotados. 18,100 km. Precio $40,440 + movilización, envío, aduana e impuestos."
    },
    {
        id: 128,
        title: "Mitsubishi Outlander Sport AWC 2025",
        price: "$19,000+",
        year: 2025,
        km: "41,400 KM",
        engine: "2.0L I-4 148HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "4x4 AWC",
        images: [
            "images/gallery/2025-mitsubishi-outlander-sport-2-0-es-awc2-0-le-awc2-0-s-awc2-0-se-awc2-0-trail-edition-awc/1.jpeg",
            "images/gallery/2025-mitsubishi-outlander-sport-2-0-es-awc2-0-le-awc2-0-s-awc2-0-se-awc2-0-trail-edition-awc/2.jpeg",
            "images/gallery/2025-mitsubishi-outlander-sport-2-0-es-awc2-0-le-awc2-0-s-awc2-0-se-awc2-0-trail-edition-awc/3.jpeg",
            "images/gallery/2025-mitsubishi-outlander-sport-2-0-es-awc2-0-le-awc2-0-s-awc2-0-se-awc2-0-trail-edition-awc/4.jpeg",
            "images/gallery/2025-mitsubishi-outlander-sport-2-0-es-awc2-0-le-awc2-0-s-awc2-0-se-awc2-0-trail-edition-awc/5.jpeg",
            "images/gallery/2025-mitsubishi-outlander-sport-2-0-es-awc2-0-le-awc2-0-s-awc2-0-se-awc2-0-trail-edition-awc/6.jpeg",
            "images/gallery/2025-mitsubishi-outlander-sport-2-0-es-awc2-0-le-awc2-0-s-awc2-0-se-awc2-0-trail-edition-awc/7.jpeg",
            "images/gallery/2025-mitsubishi-outlander-sport-2-0-es-awc2-0-le-awc2-0-s-awc2-0-se-awc2-0-trail-edition-awc/8.jpeg",
            "images/gallery/2025-mitsubishi-outlander-sport-2-0-es-awc2-0-le-awc2-0-s-awc2-0-se-awc2-0-trail-edition-awc/9.jpeg",
            "images/gallery/2025-mitsubishi-outlander-sport-2-0-es-awc2-0-le-awc2-0-s-awc2-0-se-awc2-0-trail-edition-awc/10.jpeg",
            "images/gallery/2025-mitsubishi-outlander-sport-2-0-es-awc2-0-le-awc2-0-s-awc2-0-se-awc2-0-trail-edition-awc/11.jpeg",
            "images/gallery/2025-mitsubishi-outlander-sport-2-0-es-awc2-0-le-awc2-0-s-awc2-0-se-awc2-0-trail-edition-awc/12.jpeg",
            "images/gallery/2025-mitsubishi-outlander-sport-2-0-es-awc2-0-le-awc2-0-s-awc2-0-se-awc2-0-trail-edition-awc/13.jpeg",
            "images/gallery/2025-mitsubishi-outlander-sport-2-0-es-awc2-0-le-awc2-0-s-awc2-0-se-awc2-0-trail-edition-awc/14.jpeg",
            "images/gallery/2025-mitsubishi-outlander-sport-2-0-es-awc2-0-le-awc2-0-s-awc2-0-se-awc2-0-trail-edition-awc/15.jpeg",
            "images/gallery/2025-mitsubishi-outlander-sport-2-0-es-awc2-0-le-awc2-0-s-awc2-0-se-awc2-0-trail-edition-awc/16.jpeg"
        ],
        description: "Mitsubishi Outlander Sport 2025 AWC. Motor 2.0L I-4 de 148HP, automática, tracción 4x4. Daño leve trasero derecho. Airbags intactos. 41,400 km. Precio $19,000 + movilización, envío, aduana e impuestos."
    },
    {
        id: 129,
        title: "Nissan Altima SR FWD 2025",
        price: "$12,280+",
        year: 2025,
        km: "44,900 KM",
        engine: "2.5L I-4 188HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "sedan",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "POR PEDIDO",
        images: [
            "images/gallery/2025-nissan-altima-sr-fwd/1.jpeg",
            "images/gallery/2025-nissan-altima-sr-fwd/2.jpeg",
            "images/gallery/2025-nissan-altima-sr-fwd/3.jpeg",
            "images/gallery/2025-nissan-altima-sr-fwd/4.jpeg",
            "images/gallery/2025-nissan-altima-sr-fwd/5.jpeg",
            "images/gallery/2025-nissan-altima-sr-fwd/6.jpeg",
            "images/gallery/2025-nissan-altima-sr-fwd/7.jpeg",
            "images/gallery/2025-nissan-altima-sr-fwd/8.jpeg",
            "images/gallery/2025-nissan-altima-sr-fwd/9.jpeg",
            "images/gallery/2025-nissan-altima-sr-fwd/10.jpeg",
            "images/gallery/2025-nissan-altima-sr-fwd/11.jpeg",
            "images/gallery/2025-nissan-altima-sr-fwd/12.jpeg",
            "images/gallery/2025-nissan-altima-sr-fwd/13.jpeg",
            "images/gallery/2025-nissan-altima-sr-fwd/14.jpeg",
            "images/gallery/2025-nissan-altima-sr-fwd/15.jpeg",
            "images/gallery/2025-nissan-altima-sr-fwd/16.jpeg"
        ],
        description: "Nissan Altima SR FWD 2025. Motor 2.5L I-4 de 188HP, automática. Daño frontal, parabrisas y techo. Airbags intactos. 44,900 km. Precio $12,280 + movilización, envío, aduana e impuestos."
    },
    {
        id: 130,
        title: "Nissan Ariya Engage 2025",
        price: "$15,400+",
        year: 2025,
        km: "17,100 KM",
        engine: "Eléctrico",
        transmission: "Automático",
        fuel: "Eléctrico",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "⚡ ELÉCTRICO",
        images: [
            "images/gallery/2025-nissan-ariya-engage/1.jpeg",
            "images/gallery/2025-nissan-ariya-engage/2.jpeg",
            "images/gallery/2025-nissan-ariya-engage/3.jpeg",
            "images/gallery/2025-nissan-ariya-engage/4.jpeg",
            "images/gallery/2025-nissan-ariya-engage/5.jpeg",
            "images/gallery/2025-nissan-ariya-engage/6.jpeg",
            "images/gallery/2025-nissan-ariya-engage/7.jpeg",
            "images/gallery/2025-nissan-ariya-engage/8.jpeg",
            "images/gallery/2025-nissan-ariya-engage/9.jpeg",
            "images/gallery/2025-nissan-ariya-engage/10.jpeg",
            "images/gallery/2025-nissan-ariya-engage/11.jpeg",
            "images/gallery/2025-nissan-ariya-engage/12.jpeg",
            "images/gallery/2025-nissan-ariya-engage/13.jpeg",
            "images/gallery/2025-nissan-ariya-engage/14.jpeg",
            "images/gallery/2025-nissan-ariya-engage/15.jpeg",
            "images/gallery/2025-nissan-ariya-engage/16.jpeg",
            "images/gallery/2025-nissan-ariya-engage/17.jpeg",
            "images/gallery/2025-nissan-ariya-engage/18.jpeg",
            "images/gallery/2025-nissan-ariya-engage/19.jpeg"
        ],
        description: "Nissan Ariya Engage 2025. SUV 100% eléctrico, automático. Daño trasero izquierdo. Airbags intactos. 17,100 km. Precio $15,400 + movilización, envío, aduana e impuestos."
    },
    {
        id: 131,
        title: "Nissan Frontier Pro-4X 4x4 2025",
        price: "$26,290+",
        year: 2025,
        km: "21,700 KM",
        engine: "3.8L V6 310HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "pickup",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "🔥 PRO-4X",
        images: [
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/1.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/2.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/3.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/4.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/5.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/6.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/7.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/8.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/9.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/10.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/11.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/12.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/13.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/14.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/15.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/16.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/17.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/18.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/19.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/20.jpeg",
            "images/gallery/2025-nissan-frontier-pro-4x-4x4/21.jpeg"
        ],
        description: "Nissan Frontier Pro-4X 2025, 4x4, doble cabina. Motor 3.8L V6 de 310HP, automática. Daño frontal y trasero. Airbags intactos. 21,700 km. Precio $26,290 + movilización, envío, aduana e impuestos."
    },
    {
        id: 132,
        title: "Nissan Kicks Play S 2025",
        price: "$5,320+",
        year: 2025,
        km: "17,000 KM",
        engine: "1.6L I-4 122HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "🔥 LOMITO",
        images: [
            "images/gallery/2025-nissan-kicks-play-s-lomitoooo/1.jpeg",
            "images/gallery/2025-nissan-kicks-play-s-lomitoooo/2.jpeg",
            "images/gallery/2025-nissan-kicks-play-s-lomitoooo/3.jpeg",
            "images/gallery/2025-nissan-kicks-play-s-lomitoooo/4.jpeg",
            "images/gallery/2025-nissan-kicks-play-s-lomitoooo/5.jpeg",
            "images/gallery/2025-nissan-kicks-play-s-lomitoooo/6.jpeg",
            "images/gallery/2025-nissan-kicks-play-s-lomitoooo/7.jpeg",
            "images/gallery/2025-nissan-kicks-play-s-lomitoooo/8.jpeg",
            "images/gallery/2025-nissan-kicks-play-s-lomitoooo/9.jpeg",
            "images/gallery/2025-nissan-kicks-play-s-lomitoooo/10.jpeg",
            "images/gallery/2025-nissan-kicks-play-s-lomitoooo/11.jpeg",
            "images/gallery/2025-nissan-kicks-play-s-lomitoooo/12.jpeg",
            "images/gallery/2025-nissan-kicks-play-s-lomitoooo/13.jpeg",
            "images/gallery/2025-nissan-kicks-play-s-lomitoooo/14.jpeg",
            "images/gallery/2025-nissan-kicks-play-s-lomitoooo/15.jpeg"
        ],
        description: "Nissan Kicks Play S 2025. ¡LOMITO! Motor 1.6L I-4 de 122HP, automático. Daño leve frontal izquierdo. Airbags explotados. 17,000 km. Precio $5,320 + movilización, envío, aduana e impuestos."
    },
    {
        id: 133,
        title: "Nissan Kicks SV 2025",
        price: "$10,300+",
        year: 2025,
        km: "2,600 KM",
        engine: "2.0L I-4 141HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "CASI NUEVO",
        images: [
            "images/gallery/2025-nissan-kicks-sv/1.jpeg",
            "images/gallery/2025-nissan-kicks-sv/2.jpeg",
            "images/gallery/2025-nissan-kicks-sv/3.jpeg",
            "images/gallery/2025-nissan-kicks-sv/4.jpeg",
            "images/gallery/2025-nissan-kicks-sv/5.jpeg",
            "images/gallery/2025-nissan-kicks-sv/6.jpeg",
            "images/gallery/2025-nissan-kicks-sv/7.jpeg",
            "images/gallery/2025-nissan-kicks-sv/8.jpeg",
            "images/gallery/2025-nissan-kicks-sv/9.jpeg",
            "images/gallery/2025-nissan-kicks-sv/10.jpeg",
            "images/gallery/2025-nissan-kicks-sv/11.jpeg",
            "images/gallery/2025-nissan-kicks-sv/12.jpeg",
            "images/gallery/2025-nissan-kicks-sv/13.jpeg",
            "images/gallery/2025-nissan-kicks-sv/14.jpeg",
            "images/gallery/2025-nissan-kicks-sv/15.jpeg",
            "images/gallery/2025-nissan-kicks-sv/16.jpeg"
        ],
        description: "Nissan Kicks SV 2025. Motor 2.0L I-4 de 141HP, automático. Daño leve, golpe en trasero izquierdo. Airbags intactos. Solo 2,600 km. Precio $10,300 + movilización, envío, aduana e impuestos."
    },
    {
        id: 134,
        title: "Nissan Kicks SV AWD 4x4 2025",
        price: "$12,370+",
        year: 2025,
        km: "2,000 KM",
        engine: "2.0L I-4 141HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "4x4 AWD",
        images: [
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/1.jpeg",
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/2.jpeg",
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/3.jpeg",
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/4.jpeg",
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/5.jpeg",
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/6.jpeg",
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/7.jpeg",
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/8.jpeg",
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/9.jpeg",
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/10.jpeg",
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/11.jpeg",
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/12.jpeg",
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/13.jpeg",
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/14.jpeg",
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/15.jpeg",
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/16.jpeg",
            "images/gallery/2025-nissan-kicks-sv-intelligent-4x4-awd/17.jpeg"
        ],
        description: "Nissan Kicks SV Intelligent 4x4 AWD 2025. Motor 2.0L I-4 de 141HP, automática, tracción 4x4. Daño frontal izquierdo. Airbags intactos. Solo 2,000 km. Precio $12,370 + movilización, envío, aduana e impuestos."
    },
    {
        id: 135,
        title: "RAM 1500 Rebel 4x4 2025",
        price: "$32,800+",
        year: 2025,
        km: "94,200 KM",
        engine: "3.0L I-6 Turbo 420HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "pickup",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "🔥 REBEL 420HP",
        images: [
            "images/gallery/2025-ram-1500-rebel-4x4-57-box/1.jpeg",
            "images/gallery/2025-ram-1500-rebel-4x4-57-box/2.jpeg",
            "images/gallery/2025-ram-1500-rebel-4x4-57-box/3.jpeg",
            "images/gallery/2025-ram-1500-rebel-4x4-57-box/4.jpeg",
            "images/gallery/2025-ram-1500-rebel-4x4-57-box/5.jpeg",
            "images/gallery/2025-ram-1500-rebel-4x4-57-box/6.jpeg",
            "images/gallery/2025-ram-1500-rebel-4x4-57-box/7.jpeg",
            "images/gallery/2025-ram-1500-rebel-4x4-57-box/8.jpeg",
            "images/gallery/2025-ram-1500-rebel-4x4-57-box/9.jpeg",
            "images/gallery/2025-ram-1500-rebel-4x4-57-box/10.jpeg",
            "images/gallery/2025-ram-1500-rebel-4x4-57-box/11.jpeg",
            "images/gallery/2025-ram-1500-rebel-4x4-57-box/12.jpeg",
            "images/gallery/2025-ram-1500-rebel-4x4-57-box/13.jpeg",
            "images/gallery/2025-ram-1500-rebel-4x4-57-box/14.jpeg",
            "images/gallery/2025-ram-1500-rebel-4x4-57-box/15.jpeg"
        ],
        description: "RAM 1500 Rebel 2025, 4x4, caja 5'7. Motor 3.0L I-6 Turbo de 420HP, automática. Daño frontal. Airbags explotados. 94,200 km. Precio $32,800 + movilización, envío, aduana e impuestos."
    },
    {
        id: 136,
        title: "Toyota Tacoma SR5 2025",
        price: "$29,980+",
        year: 2025,
        km: "7,500 KM",
        engine: "2.4L Turbo 278HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "pickup",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "4x4",
        images: [
            "images/gallery/2025-toyota-tacoma-sr5/1.jpeg",
            "images/gallery/2025-toyota-tacoma-sr5/2.jpeg",
            "images/gallery/2025-toyota-tacoma-sr5/3.jpeg",
            "images/gallery/2025-toyota-tacoma-sr5/4.jpeg",
            "images/gallery/2025-toyota-tacoma-sr5/5.jpeg",
            "images/gallery/2025-toyota-tacoma-sr5/6.jpeg",
            "images/gallery/2025-toyota-tacoma-sr5/7.jpeg",
            "images/gallery/2025-toyota-tacoma-sr5/8.jpeg",
            "images/gallery/2025-toyota-tacoma-sr5/9.jpeg",
            "images/gallery/2025-toyota-tacoma-sr5/10.jpeg",
            "images/gallery/2025-toyota-tacoma-sr5/11.jpeg",
            "images/gallery/2025-toyota-tacoma-sr5/12.jpeg",
            "images/gallery/2025-toyota-tacoma-sr5/13.jpeg",
            "images/gallery/2025-toyota-tacoma-sr5/14.jpeg",
            "images/gallery/2025-toyota-tacoma-sr5/15.jpeg"
        ],
        description: "Toyota Tacoma SR5 2025, doble cabina, 4x4. Motor 2.4L Turbo de 278HP, automática. Daño por inundación. Solo 7,500 km. Precio $29,980 + movilización, envío, aduana e impuestos."
    },
    {
        id: 137,
        title: "Honda CR-V EX AWD 2026",
        price: "$24,130+",
        year: 2026,
        km: "14,900 KM",
        engine: "1.5L Turbo 190HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "2026",
        images: [
            "images/gallery/2026-honda-cr-v-ex-awd/1.jpeg",
            "images/gallery/2026-honda-cr-v-ex-awd/2.jpeg",
            "images/gallery/2026-honda-cr-v-ex-awd/3.jpeg",
            "images/gallery/2026-honda-cr-v-ex-awd/4.jpeg",
            "images/gallery/2026-honda-cr-v-ex-awd/5.jpeg",
            "images/gallery/2026-honda-cr-v-ex-awd/6.jpeg",
            "images/gallery/2026-honda-cr-v-ex-awd/7.jpeg",
            "images/gallery/2026-honda-cr-v-ex-awd/8.jpeg",
            "images/gallery/2026-honda-cr-v-ex-awd/9.jpeg",
            "images/gallery/2026-honda-cr-v-ex-awd/10.jpeg",
            "images/gallery/2026-honda-cr-v-ex-awd/11.jpeg",
            "images/gallery/2026-honda-cr-v-ex-awd/12.jpeg",
            "images/gallery/2026-honda-cr-v-ex-awd/13.jpeg",
            "images/gallery/2026-honda-cr-v-ex-awd/14.jpeg",
            "images/gallery/2026-honda-cr-v-ex-awd/15.jpeg"
        ],
        description: "Honda CR-V EX AWD 2026. Motor 1.5L Turbo de 190HP, automática, 4x4 AWD. Daño leve trasero izquierdo. Airbags explotados. 14,900 km. Precio $24,130 + movilización, envío, aduana e impuestos."
    },
    {
        id: 138,
        title: "Honda HR-V 2WD Sport 2026",
        price: "$22,000+",
        year: 2026,
        km: "11,600 KM",
        engine: "2.0L I-4 158HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "2026",
        images: [
            "images/gallery/2026-honda-hr-v-2wd-sport/1.jpeg",
            "images/gallery/2026-honda-hr-v-2wd-sport/2.jpeg",
            "images/gallery/2026-honda-hr-v-2wd-sport/3.jpeg",
            "images/gallery/2026-honda-hr-v-2wd-sport/4.jpeg",
            "images/gallery/2026-honda-hr-v-2wd-sport/5.jpeg",
            "images/gallery/2026-honda-hr-v-2wd-sport/6.jpeg",
            "images/gallery/2026-honda-hr-v-2wd-sport/7.jpeg",
            "images/gallery/2026-honda-hr-v-2wd-sport/8.jpeg",
            "images/gallery/2026-honda-hr-v-2wd-sport/9.jpeg",
            "images/gallery/2026-honda-hr-v-2wd-sport/10.jpeg",
            "images/gallery/2026-honda-hr-v-2wd-sport/11.jpeg",
            "images/gallery/2026-honda-hr-v-2wd-sport/12.jpeg",
            "images/gallery/2026-honda-hr-v-2wd-sport/13.jpeg",
            "images/gallery/2026-honda-hr-v-2wd-sport/14.jpeg",
            "images/gallery/2026-honda-hr-v-2wd-sport/15.jpeg"
        ],
        description: "Honda HR-V 2WD Sport 2026. Motor 2.0L I-4 de 158HP, automática. Airbags intactos. 11,600 km. Precio $22,000 + movilización, envío, aduana e impuestos."
    },
    {
        id: 139,
        title: "Kia Sportage LX 2026",
        price: "$16,720+",
        year: 2026,
        km: "2,800 KM",
        engine: "2.5L I-4 187HP",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "CASI NUEVO",
        images: [
            "images/gallery/2026-kia-sportage-lx/1.jpeg",
            "images/gallery/2026-kia-sportage-lx/2.jpeg",
            "images/gallery/2026-kia-sportage-lx/3.jpeg",
            "images/gallery/2026-kia-sportage-lx/4.jpeg",
            "images/gallery/2026-kia-sportage-lx/5.jpeg",
            "images/gallery/2026-kia-sportage-lx/6.jpeg",
            "images/gallery/2026-kia-sportage-lx/7.jpeg",
            "images/gallery/2026-kia-sportage-lx/8.jpeg",
            "images/gallery/2026-kia-sportage-lx/9.jpeg",
            "images/gallery/2026-kia-sportage-lx/10.jpeg",
            "images/gallery/2026-kia-sportage-lx/11.jpeg",
            "images/gallery/2026-kia-sportage-lx/12.jpeg",
            "images/gallery/2026-kia-sportage-lx/13.jpeg",
            "images/gallery/2026-kia-sportage-lx/14.jpeg",
            "images/gallery/2026-kia-sportage-lx/15.jpeg",
            "images/gallery/2026-kia-sportage-lx/16.jpeg"
        ],
        description: "Kia Sportage LX 2026. Motor 2.5L I-4 de 187HP, automático. Daño lateral derecho. Airbags explotados. Solo 2,800 km. Precio $16,720 + movilización, envío, aduana e impuestos."
    },
    {
        id: 140,
        title: "Jeep Wrangler Sport S 2 Puertas 4x4",
        price: "$21,700+",
        year: 2023,
        km: "64,000 KM",
        engine: "3.6L V6",
        transmission: "Automático",
        fuel: "Gasolina",
        bodyType: "suv",
        origin: "importado",
        condition: "seminuevo",
        availability: "por_pedido",
        badge: "2 PUERTAS",
        images: [
            "images/gallery/jeep-wrangler-sport-s-2-puertas-4x4/1.jpg",
            "images/gallery/jeep-wrangler-sport-s-2-puertas-4x4/2.jpg",
            "images/gallery/jeep-wrangler-sport-s-2-puertas-4x4/3.jpg",
            "images/gallery/jeep-wrangler-sport-s-2-puertas-4x4/4.jpg",
            "images/gallery/jeep-wrangler-sport-s-2-puertas-4x4/5.jpg",
            "images/gallery/jeep-wrangler-sport-s-2-puertas-4x4/6.jpg",
            "images/gallery/jeep-wrangler-sport-s-2-puertas-4x4/7.jpg",
            "images/gallery/jeep-wrangler-sport-s-2-puertas-4x4/8.jpg",
            "images/gallery/jeep-wrangler-sport-s-2-puertas-4x4/9.jpg",
            "images/gallery/jeep-wrangler-sport-s-2-puertas-4x4/10.jpg",
            "images/gallery/jeep-wrangler-sport-s-2-puertas-4x4/11.jpg",
            "images/gallery/jeep-wrangler-sport-s-2-puertas-4x4/12.jpg",
            "images/gallery/jeep-wrangler-sport-s-2-puertas-4x4/13.jpg",
            "images/gallery/jeep-wrangler-sport-s-2-puertas-4x4/14.jpg"
        ],
        description: "Jeep Wrangler Sport S 2 puertas, 4x4. Motor 3.6L V6, automático. 64,000 km. Ubicación USA. Nivel de daño leve. Airbags sin daño. Bajo pedido (promedio 2 meses Puerto Libre o nacional). Precio $21,700 + movilización, envío, aduana e impuestos."
    }
];

// ============================================
//  COMBINACIÓN DE TODOS LOS VEHÍCULOS
// ============================================
const allVehicles = [...vehiclesSeminuevos, ...vehicles0km];

/**
 *  NÚMERO DE WHATSAPP PARA CONSULTAS
 */
const WHATSAPP_NUMBER = "584147977832";

/**
 *  INFORMACIÓN DE LA EMPRESA
 */
const COMPANY_INFO = {
    name: "SemiNuevos Agency",
    slogan: "Conduce a Otro Nivel",
    phone: "+58 414-797-7832",
    email: "info@seminuevosagency.com",
    address: "Porlamar, Isla de Margarita, Venezuela",
    hours: "Lun - Sáb: 9:00 AM - 7:00 PM",
    socialMedia: {
        facebook: "#",
        instagram: "https://www.instagram.com/seminuevosagency/",
        tiktok: "#",
        youtube: "#"
    }
};

/**
 *  LABELS PARA LOS FILTROS
 */
const BODY_TYPE_LABELS = {
    sedan: "Sedán",
    suv: "SUV",
    pickup: "Pickup",
    deportivo: "Deportivo",
    coupe: "Coupé",
    hatchback: "Hatchback"
};

const ORIGIN_LABELS = {
    nacional: "Nacional",
    importado: "Importado"
};

const CONDITION_LABELS = {
    seminuevo: "Seminuevo",
    "0km": "0 KM"
};

const AVAILABILITY_LABELS = {
    entrega_inmediata: "Entrega Inmediata",
    por_pedido: "Por Pedido"
};

